Possibility to validate user data was added.
ViktoriiaKlymenko/HomeWorks pull request #10
Opened 2021-06-03 15:10 UTC by ViktoriiaKlymenko

2021-06-05 08:23 UTC, serhii-shkodenko requested changes

2021-06-05 08:23 UTC, serhii-shkodenko commented on PastriesDelivery/Program.cs
> +            } while (DataValidator.ValidateAddress(user.Address));
А как-то отказаться от ввода адреса можно вообще?

2021-06-05 08:23 UTC, serhii-shkodenko commented on PastriesDelivery/Program.cs
> +            } while (DataValidator.ValidatePhoneNumber(user.PhoneNumber));
А как-то отказаться от ввода адреса можно вообще?

2021-06-05 09:39 UTC, ViktoriiaKlymenko commented on PastriesDelivery/Program.cs
> +            } while (DataValidator.ValidateAddress(user.Address));
Та нет, а куда ж доставлять тогда, если пользователь адрес не введет?

2021-06-05 09:42 UTC, serhii-shkodenko commented on PastriesDelivery/Program.cs
> +            } while (DataValidator.ValidateAddress(user.Address));
Тогда нужно отменить весь заказ.

2021-06-11 20:39 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-06-12 10:38 UTC, merged