System of auxiliary types, which allows to interact with the system.
ViktoriiaKlymenko/HomeWorks pull request #3
Opened 2021-04-23 12:01 UTC by ViktoriiaKlymenko

2021-04-27 15:22 UTC, serhii-shkodenko requested changes

2021-04-27 15:22 UTC, serhii-shkodenko commented on Contracts/IDataDisplayer.cs
> +    interface IDataDisplayer
Не хватает модификатора доступа.

2021-04-27 15:22 UTC, serhii-shkodenko commented on Contracts/IDataDisplayer.cs
> +        public void DisplayAvailableProducts();
А здесь модификатор доступа лишний. По умолчанию, члены интерфейса имеют пуличный уровень доступа.

2021-04-27 15:22 UTC, serhii-shkodenko commented on Contracts/IDataDisplayer.cs
> +        public void DisplayProviderData();
А здесь модификатор доступа лишний. По умолчанию, члены интерфейса имеют пуличный уровень доступа.

2021-04-27 15:22 UTC, serhii-shkodenko commented on Contracts/IOffersMaker.cs
> +    interface IOffersMaker
Не хватает модификатора доступа.

2021-04-27 15:22 UTC, serhii-shkodenko commented on Contracts/IOffersMaker.cs
> +        public void AddNewOffer(Pastry product);
А здесь модификатор доступа лишний. По умолчанию, члены интерфейса имеют пуличный уровень доступа.

2021-04-27 15:22 UTC, serhii-shkodenko commented on Contracts/IOffersMaker.cs
> +        public string ConfirmOffer();
А здесь модификатор доступа лишний. По умолчанию, члены интерфейса имеют пуличный уровень доступа.

2021-04-27 15:22 UTC, serhii-shkodenko commented on Contracts/IOffersMaker.cs
> +        public void AcceptData(Pastry product);
А здесь модификатор доступа лишний. По умолчанию, члены интерфейса имеют пуличный уровень доступа.

2021-04-27 15:22 UTC, serhii-shkodenko commented on Contracts/IOrderMaker.cs
> +        public string ConfirmOrder();
А здесь модификатор доступа лишний. По умолчанию, члены интерфейса имеют пуличный уровень доступа.

2021-04-27 15:22 UTC, serhii-shkodenko commented on Contracts/IOrderMaker.cs
> +    interface IOrderMaker
Не хватает модификатора доступа.

2021-04-27 15:22 UTC, serhii-shkodenko commented on Managers/BusinessClientManager.cs
> +    class BusinessClientManager : IOrderMaker
Не хватает модификатора доступа.

2021-04-27 15:22 UTC, serhii-shkodenko commented on Models/Consumer.cs
> +    public abstract class Consumer
Этот пустой класс не нужен, его можно удалить.

2021-04-27 15:22 UTC, serhii-shkodenko commented on Program.cs
> -        private static IEnumerable<decimal> NormalizeCurrencies(IEnumerable<decimal> prices, IEnumerable<string> currencies)
Удалять первое задание для выполнения третьего не нужно. Лучше переписать код так, чтобы сохранить все задания. Я на встрече об этом говорил, в частности, можно создать разные проекты.

2021-04-27 16:49 UTC, serhii-shkodenko requested changes
Ты движешься в правильном направлении, но пока есть что еще можно поправить.

2021-04-27 16:49 UTC, serhii-shkodenko commented on PastriesDelivery/Storage/AvailableProducts.cs
> +    static public class AvailableProducts
Этот класс очень желетально переделать. Хранить данные в статическом классе - это плохая идея. Ведь эти данные могут быть изменены любы потоком. Здесь хорошо бы сделать класс, который в качестве зависимости нужно будет передавать другим классам, манипулирующими данными. В этих классах следует в качестве параметра в конструкторе предумотреть не конкретный класс, а абстрацию, что позволит соблюсти Dependency inversion principle.

2021-04-27 16:49 UTC, serhii-shkodenko commented on PastriesDelivery/Storage/EndUserStorage.cs
> +    class EndUserStorage
Не хватает модификатора доступа.

2021-04-27 16:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +    class BusinessClientUI : ConsumerUI, IDataDisplayer
Не хватает модификатора доступа.

2021-04-27 16:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +    class ConsumerUI
Не хватает модификатора доступа.

2021-04-27 16:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/EndUserUI.cs
> +    class EndUserUI : ConsumerUI, IDataDisplayer
Не хватает модификатора доступа.

2021-05-04 20:14 UTC, serhii-shkodenko requested changes

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +        public BusinessClientManager(AvailableProducts availableProducts)
Нарушение Dependency inversion principle. Используй интерфейсы.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +                    Messenger.ShowUnavailableAmountMessage();
Этот класс содержит методы для работы с бизнес логикой. Поэтому он не должен содержать зависимостей от классов, которые осуществляют управление пользовательским выводом. Лучше из классов, которые выводят пользовательский интерфейс, обращаться к зависимостям, которые позволяют работать с бизнес логикой.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +            Messenger.ShowConfirmMessage();
Этот класс содержит методы для работы с бизнес логикой. Поэтому он не должен содержать зависимостей от классов, которые осуществляют управление пользовательским выводом. Лучше из классов, которые выводят пользовательский интерфейс, обращаться к зависимостям, которые позволяют работать с бизнес логикой.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +            Messenger.ShowOrderAcceptedMessage();
Этот класс содержит методы для работы с бизнес логикой. Поэтому он не должен содержать зависимостей от классов, которые осуществляют управление пользовательским выводом. Лучше из классов, которые выводят пользовательский интерфейс, обращаться к зависимостям, которые позволяют работать с бизнес логикой.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/EndUserManager.cs
> +        public EndUserManager(AvailableProducts availableProducts)
Нарушение Dependency inversion principle. Используй интерфейсы.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/EndUserManager.cs
> +            Messenger.ShowConfirmMessage();
Этот класс содержит методы для работы с бизнес логикой. Поэтому он не должен содержать зависимостей от классов, которые осуществляют управление пользовательским выводом. Лучше из классов, которые выводят пользовательский интерфейс, обращаться к зависимостям, которые позволяют работать с бизнес логикой.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/EndUserManager.cs
> +            Messenger.ShowOrderAcceptedMessage();
Этот класс содержит методы для работы с бизнес логикой. Поэтому он не должен содержать зависимостей от классов, которые осуществляют управление пользовательским выводом. Лучше из классов, которые выводят пользовательский интерфейс, обращаться к зависимостям, которые позволяют работать с бизнес логикой.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/EndUserManager.cs
> +                    Messenger.ShowUnavailableAmountMessage();
Этот класс содержит методы для работы с бизнес логикой. Поэтому он не должен содержать зависимостей от классов, которые осуществляют управление пользовательским выводом. Лучше из классов, которые выводят пользовательский интерфейс, обращаться к зависимостям, которые позволяют работать с бизнес логикой.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/ProviderManager.cs
> +            Messenger.ShowOfferAcceptedMessage();
Этот класс содержит методы для работы с бизнес логикой. Поэтому он не должен содержать зависимостей от классов, которые осуществляют управление пользовательским выводом. Лучше из классов, которые выводят пользовательский интерфейс, обращаться к зависимостям, которые позволяют работать с бизнес логикой.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/ProviderManager.cs
> +            Messenger.ShowConfirmMessage();
Этот класс содержит методы для работы с бизнес логикой. Поэтому он не должен содержать зависимостей от классов, которые осуществляют управление пользовательским выводом. Лучше из классов, которые выводят пользовательский интерфейс, обращаться к зависимостям, которые позволяют работать с бизнес логикой.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Models/BusinessClient.cs
> +        static public string Adress { get; set; } = "Client adress";
Опечатка. Должно быть `Address`,

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/ProviderManager.cs
> +            pastry.Weight = Convert.ToInt32(Console.ReadLine());
Классы для работы с бизнес логикой не должны содержать элементов вывода пользовательского интерфейса.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Models/Provider.cs
> +        static public int twentyUnitsDiscount { get; set; } = 2;
Свойства должны называться в `PascalCase`.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Models/Provider.cs
> +        static public int fiftyUnitsDiscount { get; set; } = 3;
Свойства должны называться в `PascalCase`.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Models/Provider.cs
> +        static public int hundredUnitsDiscount { get; set; } = 4;
Свойства должны называться в `PascalCase`.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Storage/AvailableProducts.cs
> +    public class AvailableProducts
Этот класс должен реализовывать интерфейс, чтобы удовлетворить Dependency inversion principle. Тогда в конструкторах других классов в качестве параметра ты будешь указывать этот интерфейс, а передавать туда будешь твой класс.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Storage/AvailableProducts.cs
> +        public Provider Provider { get; }
Здесь нет необходимости в этом свойстве. Лучше удалить.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Models/Provider.cs
> +    public class Provider
Этот класс лучше сделать статическим и переназвать, например, `UIConstatntsProvider`. Это имя больше соответвует его предназначению.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Models/EndUser.cs
> +    public class EndUser
Этот класс лучше удалить совсем, нужные свйоства перенести в `UIConstatntsProvider`.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Models/Consumer.cs
> +    public abstract class Consumer
Пустые классы, как и интерфейсы считаются плохой практикой и использоваться не должны. Удали, пожалуйста.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Program.cs
> +            var businessClientStorage = new BusinessClientStorage();
Все эти три хранилища лучше объединить в одно. Их нужно будет передавать в конструкторы классов, которые обрабатывают бизнес логику.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Storage/BusinessClientStorage.cs
> +        private List<Pastry> products = new List<Pastry>();
Это очень хорошо, что ты понимаешь, что стоит за свойствами, однако здесь нет необходимости использовать поля для храненеия данных. Просто ииспользуй автосвойства. Этого достаточно.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Storage/AvailableProducts.cs
> +        private List<Pastry> products = new List<Pastry>();
Это очень хорошо, что ты понимаешь, что стоит за свойствами, однако здесь нет необходимости использовать поля для храненеия данных. Просто ииспользуй автосвойства. Этого достаточно.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/Storage/EndUserStorage.cs
> +        private List<Pastry> products = new List<Pastry>();
Это очень хорошо, что ты понимаешь, что стоит за свойствами, однако здесь нет необходимости использовать поля для храненеия данных. Просто ииспользуй автосвойства. Этого достаточно.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        public BusinessClientUI(AvailableProducts availableProducts)
Нарушается принцип Dependency inversion principle. Используй, пожалуйста, интерфейсы.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/UI/EndUserUI.cs
> +        public EndUserUI(AvailableProducts availableProducts)
Нарушается принцип Dependency inversion principle. Используй, пожалуйста, интерфейсы.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +    internal class ConsumerUI
Я не вижу необходимости в этом классе. Предлагаю его удалить.

2021-05-04 20:14 UTC, serhii-shkodenko commented on PastriesDelivery/UI/UserUI.cs
> +    public class UserUI
Я не вижу необходимости в этом классе. Предлагаю его удалить.

2021-05-05 13:20 UTC, ViktoriiaKlymenko commented on PastriesDelivery/Program.cs
> +            var businessClientStorage = new BusinessClientStorage();
А как их можно в одно объединить? Тут же получается отдельно хранилища для заказаных товаров и отдельно хранилище для доступных товаров. Ну можно EndUserStorage и BusinessClientStorage объединить, это понятно. Не понятно как их все вместе

2021-05-05 13:42 UTC, ViktoriiaKlymenko commented on PastriesDelivery/Models/EndUser.cs
> +    public class EndUser
В другом комментарии ты написал "Этот класс (Provider) лучше сделать статическим и переназвать, например, UIConstatntsProvider. Это имя больше соответвует его предназначению." Там же получается будут находится свойства соответствующие поставщику, а здесь ты предлагаешь перенести свойства соответствующие конечному пользователю(физическому лицу, не бизнес клиенту) туда же к провайдеру. Разве так можно? Они ж перемешаются. Может я не до конца понимаю сути класса UIConstatntsProvider, который ты предлагаешь сделать

2021-05-05 19:19 UTC, serhii-shkodenko commented on PastriesDelivery/Models/EndUser.cs
> +    public class EndUser
Да, в принципе ты можешь разделить константы на области определенные, однако можно глобальные константы записать и в один файл.

2021-05-11 22:08 UTC, serhii-shkodenko requested changes

2021-05-11 22:08 UTC, serhii-shkodenko commented on PastriesDelivery/Contracts/IOrderMaker.cs
> +        Pastry ChooseProduct(string idAndAmount, Storage storage);
Здесь в параметрах метода неоптимально делать параметр для хранилища. Хранилище через интерфейс может быть внедрено в класс, реализующий `IOrderMaker`. 

Интерфейс - это про поведение, то есть что именно должен делать класс, его реализующий, а параметр `Storage storage` можно отнести в данном случае к детали реализации, которая относится уже к классу.

2021-05-11 22:08 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +        private readonly IList<Pastry> _availableProducts = new List<Pastry>();
А зачем тебе это поле, если у тебя есть `IStorage storage`? Возьми сохрани этот объект в приватное `readonly` поле и обращайся к нему из методов при необходимости, в том числе и доставай доступные продукты. Это будет оптимально.

2021-05-11 22:08 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +            var id = Convert.ToInt32(idAndAmount.Split(" ", StringSplitOptions.RemoveEmptyEntries)[0]);
Такие проверки лучше сделать в слое для работы с UI. А сюда уже передавать валидные данные.

2021-05-11 22:08 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +            businessClientStorage.Users.Add(businessClient);
Этот метод после внедрения зависимости с храналищем лучше переписать так:
`_storage.Users.Add(businessClient);`

Возможно, лучше сменить возвращаемый тип метода на `void`. авь во всем ПР, пожалуйста.

2021-05-11 22:08 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +            businessClientStorage.Pastries.Add(pastry);
Эту строку после внедрения зависимости с храналищем лучше переписать так:
`_storage.Pastries.Add(pastry);`

Возможно, лучше сменить возвращаемый тип метода на `void`. Поправь во всем ПР, пожалуйста.

2021-05-11 22:08 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessProviderManager.cs
> +        public Storage AddNewOffer(Storage storage, Pastry pastry, User user)
Лучше сделать так, чтобы класс `BusinessProviderManager` через механизм внедрения зависимостей имел правитное `readonly `поле, которое и содержало бы `IStorage` объект. К этому объекту и стоит обращаться, чятобы записывать приходящие в параметрах объекты.

2021-05-11 22:08 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/ConsumerManager.cs
> +        private readonly IList<Pastry> _availableProducts;
А зачем тебе это поле, если у тебя есть `IStorage storage`? Возьми сохрани этот объект в приватное `readonly` поле и обращайся к нему из методов при необходимости, в том числе и доставай доступные продукты. Это будет оптимально.

2021-05-11 22:08 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/ConsumerManager.cs
> +            var id = Convert.ToInt32(idAndAmount.Split(" ", StringSplitOptions.RemoveEmptyEntries)[0]);
Эти проверки логчнее сделать в слое для работы с UI.

2021-05-11 22:08 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        private readonly IList<Pastry> _availableProducts = new List<Pastry>();
А зачем тебе это поле, если у тебя есть `IStorage storage`? Возьми сохрани этот объект в приватное `readonly` поле и обращайся к нему из методов при необходимости, в том числе и доставай доступные продукты. Это будет оптимально.

2021-05-11 22:08 UTC, serhii-shkodenko commented on PastriesDelivery/UI/Messenger.cs
> +        private readonly IList<Pastry> _availableProducts;
А зачем тебе это поле, если у тебя есть `IStorage storage`? Возьми сохрани этот объект в приватное `readonly` поле и обращайся к нему из методов при необходимости, в том числе и доставай доступные продукты. Это будет оптимально.

2021-05-13 19:49 UTC, serhii-shkodenko requested changes
Ты на верном пути, я пока есть, что еще можно поправить.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/ConsumerManager.cs
> +        public Storage SendOrderToStorage(Storage storage, Pastry pastry)
Забыла переписать этот метод. Здесь лучше убрать из параметров `storage` и использовать твою приватную переменную `_storage`.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/ConsumerManager.cs
> +        public Storage SendUserToStorage(Storage storage, User consumer)
Забыла переписать этот метод. Здесь лучше убрать из параметров `storage` и использовать твою приватную переменную `_storage`.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/ConsumerManager.cs
> +        public Storage SendUserToStorage(Storage storage, User consumer)
В имени метода не стоит конкретизировать, куда ты сохраняешь объект. Достаточно будет назвать его что-то типа `SaveUser` или `CreateUser`.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/ConsumerManager.cs
> +        public Storage SendOrderToStorage(Storage storage, Pastry pastry)
В имени метода не стоит конкретизировать, куда ты сохраняешь объект. Достаточно будет назвать его что-то типа `SaveOrder` или `CreateOrder`.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/Program.cs
> +                static string DetectUser()
Отлично, что ты научилась пользоваться local functions, но здесь их использование избыточно. Здесь ты создала семантическую значимую обертку над `Console.ReadLine()`. Кроме того, этот метод ты больше нигде не используется, поэтому будет лучше оставить, как есть, то есть просто использовать `Console.ReadLine()`.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/Program.cs
> +                    var manager = new BusinessProviderManager(storage);
Создание объекта лучше выенсти из цикла. Ты его используешь на протяжении всей работы программы.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        public bool CheckForDataPrescence()
Этот метод лучше разместить в бизнес слое и вызывать его уже оттуда.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        public BusinessClientUI(IStorage storage)
Когда ты реализуешь предудшие рекомендации, эта зависимость тебе не нужна будет.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        public void DisplayAvailableProducts()
Этот метод лучше разместить в бизнес слое и вызывать его уже оттуда. Здесь лучше оставить только работу с консолью.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +        public ConsumerUI(IStorage storage)
Когда ты реализуешь предудшие рекомендации, эта зависимость тебе не нужна будет.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +        public bool CheckForDataPrescence()
Этот метод лучше разместить в бизнес слое и вызывать его уже оттуда.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +        public void DisplayAvailableProducts()
Этот метод лучше разместить в бизнес слое и вызывать его уже оттуда. Здесь лучше оставить только работу с консолью.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/Messenger.cs
> +        internal void ShowUnavailableAmountMessage(int id, int amount)
Этот метод стоит разделить на две части. Логику проверки доступности лучше выделить в бизнес слой, а здесь оставить только вывод сообщения.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ProviderUI.cs
> +            pastry.Weight = Convert.ToInt32(Console.ReadLine());
Здесь будет исключение, если пользователь введет не число, а текст. Это нужно как-то обрабатывать.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ProviderUI.cs
> +            pastry.Price = Convert.ToDecimal(Console.ReadLine());
Здесь будет исключение, если пользователь введет не число, а текст. Это нужно как-то обрабатывать.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ProviderUI.cs
> +            pastry.Amount = Convert.ToInt32(Console.ReadLine());
Здесь будет исключение, если пользователь введет не число, а текст. Это нужно как-то обрабатывать.

2021-05-13 19:49 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ProviderUI.cs
> +        private int SetId()
Логика присвоения Id лучше всего стоит размещать либо в бизнес слое, либо в слое для работы с данными. Лучше перенести метод куда-то туда.

2021-05-14 13:29 UTC, ViktoriiaKlymenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +        public void DisplayAvailableProducts()
Так тут же по сути только и вывод на консоль, в чем смысл перемещать его в бизнес слой?

2021-05-14 22:48 UTC, serhii-shkodenko requested changes

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +            var pastry = new Pastry();
Для того чтобы получить объект по его свойству из коллекции достаточно сделать:
`return _storage.Pastries.FirstOrDefault(pastry => pastry.Id == id);`

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Storage/Storage.cs
> +        public List<StorageType> Type { get; set; }
Если я понял, ты хотела предусмотреть возможность создания двух разных хранилищ, которые отличаются только типом. Почему-то ты здесь список, хотя должено быть просто свойство типа `StorageType`.

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +                if (_storage.Type[i] == StorageType.AvailableProducts)
Такую проверку лучше исключить из цикла. Более того, ее можно сделать во время сохранения твоего `IStorage` в конструкторе. В случае если тебе пришло хранилище не того типа, можно бросать исключение.

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +            foreach (var pastry in _storage.Pastries)
Чтобы уменьшить количество доступного для заказа товара, достаточно сделать:
`_storage.Pastries.FirstOrDefault(pastry => pastry.Id == id)?.Amount -= amount;
`
Подумай, как можно проверить, чтобы не уйти в негативное количество. 

Поскольку тебе нужен здесь Id, лучше сделать это все в методе `ChooseProduct()`, где он у тебя уже есть.

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +                    if (amount < product.Amount)
Вероятность того, что количество заказанной выпечки будет меньшим, чем доступное количество, будет намного выше того, что они будут равны. Получается для большинства случаев ты делаешь лишнюю проверку, поэтому код для проверки с  `<`  должен быть выше, чем с `==`. 

Если во время выполнения ты зашла в какую-то проверку, то сделаей досрочный выход из метода с помощью `return`, потому что количество доступной для заказа выпечки не может быть одновременно меньше запрашиваемого и быть равным ему.

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessProviderManager.cs
> +                if (_storage.Type[i] == StorageType.AvailableProducts)
Такую проверку лучше исключить из цикла. Более того, ее можно сделать во время сохранения твоего `IStorage` в конструкторе. В случае если тебе пришло хранилище не того типа, можно бросать исключение.

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessProviderManager.cs
> +                    if (i < pastry.Id)
Твое решение приведет к следующему:

Исходная коллекция:
```
Pastry { Id = 1 }
Pastry { Id = 2 }
Pastry { Id = 3 }
```

Состояние после удаления элемента с Id = 2:
```
Pastry { Id = 1 }
Pastry { Id = 3 }
```

Состояние после работы метода:
```
Pastry { Id = 1 }
Pastry { Id = 3 }
Pastry { Id = 3 }
```

Для нахождения доступного для присвоения Id предложу два метода:
1. Перебор в цикле Id. Значение Id сохраняется вне цикла. В каждой итерации сравнивается значение с записанным вне цикла, если этот текущий Id больше него, значение переписывается и так далее. 
2. Метод расширения `Max()` из `System.Linq`.

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/ConsumerManager.cs
> +        public Pastry ChooseProduct(int id, int amount)
Это точно такой же метод как и в `BusinessClientManager()`. Это нарушает принцип DRY. Попробуй выделить общий класс для наследования.

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +            foreach (var ch in param)
Для проверки валидности введенного числа используй, например, `int.TryParse()`.

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +                    Console.Write("not digit");
Если я захочу проверить число 100000, мне шесть раз выведет это одно и то же сообщение. Я не вижу в этом практической пользы, удали эту строку.

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +            Console.Write("digit");
Если я захочу проверить число 100000, мне шесть раз выведет это одно и то же сообщение. Я не вижу в этом практической пользы, удали эту строку.

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Program.cs
> +                        Name = "Some name",
Было бы лучше просить пользователя ввести свое имя.

2021-05-14 22:48 UTC, serhii-shkodenko commented on PastriesDelivery/Program.cs
> +                        Name = "Some name",
Было бы лучше просить пользователя ввести свое имя.

2021-05-15 10:22 UTC, ViktoriiaKlymenko commented on PastriesDelivery/Managers/BusinessProviderManager.cs
> +                if (_storage.Type[i] == StorageType.AvailableProducts)
это тогда надо создавать в Program.cs две сущности Storage, одну с типом AvailableProducts, а другая с типом UserOrders? и передавать в конструкторы классов с нужным типом хранилища?

2021-05-23 15:47 UTC, serhii-shkodenko requested changes

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/Contracts/IOrderMaker.cs
> +        public void SaveOrder(Pastry pastry);
Члены интерфейсов по умолчанию имеют уровень доступа `public`, поэтому его опускают. Удали, пожалуйста, этот модификатор.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/Contracts/IOrderMaker.cs
> +        public void SaveUser(User businessClient);
Члены интерфейсов по умолчанию имеют уровень доступа `public`, поэтому его опускают. Удали, пожалуйста, этот модификатор.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/СustomerManager.cs
> +        private readonly IStorage _userOrders;
И `_availableProducts `и `_userOrders` имеют один и тот же тип, то есть ты создаешь две копии одногои того же объекта. Достаточно только одного объекта, скажем, `_storage`. И в классах с бизнес логикой можно определить методы для манипулирования нужными объектами, если нужны продукты - напиши метод для получения доступных для заказа продуктов, если заказы - напиши метод для получения заказв из этого объекта `_storage`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/СustomerManager.cs
> +        public СustomerManager(IStorage availableProducts, IStorage userOrders)
Дублирование одного того же объекта. Удали лишний. Смотри комментарий выше.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/СustomerManager.cs
> +        private readonly IStorage _userOrders;
Поскольку ты от этого класса наследуешься, ты может предоставлять эту зависимость типа `IStorage` для своих наследников. Для этого переделай это поле в свойство (с только одним геттером) и поменяй уровень доступа с `private` на `protected`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +        private readonly IStorage _userOrders;
Когда реализуешь предложенный ниже подход, то это поле тебе не понадобится, у тебя будет `protected` свойство. Поэтому удали его.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +        public int ValidateIsDigit(string param)
Имя метода не соответсвует его сути. Ты в нем делаешь парсинг строки в числовой тип, поэтому было бы логичнее назвать его как-то с глаголом Parse. Однако этот метод - просто обертка над `TryParse()`, поэтому удали этот метод и класс целиком, а в нужных местах просто используй `TryParse()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +            if (Int32.TryParse(param, out int result))
В четвертой спецификации языка C# есть рекомендация использовать алиасы типов, а не их полные CLR имена. Поэтому пиши `int.TryParse()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/Storage/Storage.cs
> +        public StorageType Type { get; set; }
Это свойство по сути тебе и не нужно. У тебя твое хранилище и так хранит данные всех типов. Поэтому просто удали его, и тип `StorageType` тоже.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        public BusinessClientUI(IStorage availableProducts)
Здесь в качестве зависимости должен приходит класс, отвечсающий за бизнес логику, а не твое хранилище. Я в пятницу говорил о протекании слоев и почему не стоит делать так, чтобы слой UI знал о слоев БД. 

Поэтому удали эту зависимость и сделай так, чтобы сюда приходил класс с нужной тебе бизнес логикой и используй методы уже оттуда.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        public static string GetAddress()
Этот метод не несет в себе дополнительного качества, поэтому его лучше удалить, а внужных местах просто использовать `Console.ReadLine()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        public static string GetPhoneNumber()
Этот метод не несет в себе дополнительного качества, поэтому его лучше удалить, а внужных местах просто использовать `Console.ReadLine()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        public static string GetOrder()
Этот метод не несет в себе дополнительного качества, поэтому его лучше удалить, а внужных местах просто использовать `Console.ReadLine()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        public string ConfirmOrder()
Этот метод не несет в себе дополнительного качества, поэтому его лучше удалить, а внужных местах просто использовать `Console.ReadLine()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        internal static string GetUserName()
Этот метод не несет в себе дополнительного качества, поэтому его лучше удалить, а внужных местах просто использовать `Console.ReadLine()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +        internal static int ExtractId(string idAndAmount)
Этот метод просто обертка, поэтому в нужном месте просто используй `Convert.ToInt32()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/BusinessClientUI.cs
> +            var amount = Convert.ToInt32(idAndAmount.Split(" ", StringSplitOptions.RemoveEmptyEntries)[1]);
Этот метод просто обертка, поэтому в нужном месте просто используй `Convert.ToInt32()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +        public static string GetAddress()
Этот метод не несет в себе дополнительного качества, поэтому его лучше удалить, а внужных местах просто использовать `Console.ReadLine()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +        public static string GetPhoneNumber()
Этот метод не несет в себе дополнительного качества, поэтому его лучше удалить, а внужных местах просто использовать `Console.ReadLine()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +        public static string GetOrder()
Этот метод не несет в себе дополнительного качества, поэтому его лучше удалить, а внужных местах просто использовать `Console.ReadLine()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +        public string ConfirmOrder()
Этот метод не несет в себе дополнительного качества, поэтому его лучше удалить, а внужных местах просто использовать `Console.ReadLine()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +        internal static string GetUserName()
Этот метод не несет в себе дополнительного качества, поэтому его лучше удалить, а внужных местах просто использовать `Console.ReadLine()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +            var id = Convert.ToInt32(idAndAmount.Split(" ", StringSplitOptions.RemoveEmptyEntries)[0]);
Этот метод просто обертка, поэтому в нужном месте просто используй `Convert.ToInt32()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +            var amount = Convert.ToInt32(idAndAmount.Split(" ", StringSplitOptions.RemoveEmptyEntries)[1]);
Этот метод просто обертка, поэтому в нужном месте просто используй `Convert.ToInt32()`.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +        private readonly IStorage _availableProducts;
Здесь в качестве зависимости должен приходит класс, отвечсающий за бизнес логику, а не твое хранилище. Я в пятницу говорил о протекании слоев и почему не стоит делать так, чтобы слой UI знал о слоев БД.

Поэтому удали эту зависимость и сделай так, чтобы сюда приходил класс с нужной тебе бизнес логикой и используй методы уже оттуда.

2021-05-23 15:47 UTC, serhii-shkodenko commented on PastriesDelivery/UI/ConsumerUI.cs
> +        public void DisplayAvailableProducts()
Поясню: список хлебобулочных изделий следует получить из бизнес слоя. То есть для получения продуктов будет использоваться метод оттуда, а здесь лучше оставить только вывод на консоль.

2021-05-26 15:11 UTC, yevhenbilushko commented on FoodDeliveryTask/Program.cs
> -            for (int i = 0; i < currenciesList.Count(); i++)
test comment

2021-05-26 18:20 UTC, yevhenbilushko commented on FoodDeliveryTask/Program.cs
>                  if (currenciesList[i] is not "USD")
please move to constant and reuse

2021-05-26 18:20 UTC, yevhenbilushko commented on FoodDeliveryTask/Program.cs
>                  if (currenciesList[i] is not "USD")
1.19 value as well

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Constants.cs
> +    public enum DiscountPercents
move this enum to separate file
one enum - one file

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Constants.cs
> +        TwentyUnits = 2,
why start from 2?

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Contracts/IBusinessClientManager.cs
> +    {
empty interface it is strange
maybe to add members?

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Contracts/ICustomerManager.cs
> +        List<Product> ExtractProducts();
what "Extract" means?

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +            if (pastry.Amount > 19 && pastry.Amount < 50)
please divide all "if" by blank line

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Managers/BusinessClientManager.cs
> +            if (pastry.Amount > 19 && pastry.Amount < 50)
please divide all "if" by blank line

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Managers/BusinessProviderManager.cs
> +            if (_storage.Products.Count is not 0)
maybe use "Any" ?

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Managers/СustomerManager.cs
> +            if (amount > pastry.Amount || amount <= 0)
this check should be in the beginning of the method

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Managers/СustomerManager.cs
> +            if (Storage.Products.Count is 0)
consider something like this
```suggestion
            return Storage.Products.Count is not 0;
```

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Managers/СustomerManager.cs
> +            if (Storage.Products.Count is 0)
consider something like this
```suggestion
            return Storage.Products.Count is not 0;
```

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Program.cs
> +        private static void Main(string[] args)
please divide this method by methods to simplify it

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Program.cs
> +            bool result;
maybe "isValid" or "isDataValid" or other option
to make it more clear

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Program.cs
> +                    var User = new User()
seems like "()" couldbe removed

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Program.cs
> +                    if (result is true)
```suggestion
                    if (result)
```

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Program.cs
> +                    if (result is false)
```suggestion
                    if (!result)
```

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Program.cs
> +                    if (result is true)
```suggestion
                    if (result)
```

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/Program.cs
> +                    if (result is false)
```suggestion
                    if (!result)
```

2021-05-26 18:20 UTC, yevhenbilushko commented on PastriesDelivery/UI/ProviderUI.cs
> +            do
please divide loops by blank line
it make code more readable

2021-05-26 18:29 UTC, ViktoriiaKlymenko commented on PastriesDelivery/Constants.cs
> +        TwentyUnits = 2,
i decided to do this enum with something like a constants. so twentyUnits - name of the constant and 2 is a number value of it. 2% discount

2021-05-26 18:32 UTC, ViktoriiaKlymenko commented on PastriesDelivery/Contracts/ICustomerManager.cs
> +        List<Product> ExtractProducts();
i meant "to take out" list of products from the whole storage, to use it then when i need excactly a list of products, not orders

2021-05-26 18:44 UTC, ViktoriiaKlymenko commented on PastriesDelivery/Contracts/IOrderMaker.cs
> +        public void SaveUser(User businessClient);
Этот интерфейс был удален за ненадобностью

2021-05-26 18:46 UTC, ViktoriiaKlymenko commented on Contracts/IOffersMaker.cs
> +    interface IOffersMaker
Этот интерфейс тоже быд удален за ненадобностью

2021-05-27 16:26 UTC, ViktoriiaKlymenko commented on PastriesDelivery/Contracts/IBusinessClientManager.cs
> +    {
I used it for some reason and forgot to delete. Now it's deleted

2021-05-27 16:31 UTC, ViktoriiaKlymenko commented on FoodDeliveryTask/Program.cs
>                  if (currenciesList[i] is not "USD")
I can't delete brakets near count(), because i couldn't then substract 1

2021-06-01 18:42 UTC, yevhenbilushko commented on PastriesDelivery/DiscountPerscentConstants.cs
> +    public enum DiscountPercents
fix "DiscountPerscentConstants.cs" name to "DiscountPercentConstants.cs"
this is not constant, this is enum so better "DiscountPercentEnum"
and type name and file name should be the same
so please choose the name and make it the same

2021-06-01 18:42 UTC, yevhenbilushko commented on PastriesDelivery/Program.cs
> +
remove line

2021-06-01 18:42 UTC, yevhenbilushko commented on PastriesDelivery/RoleConstants.cs
> +    public enum Role
rename file to "Role" as well

2021-06-01 18:42 UTC, yevhenbilushko commented on PastriesDelivery/Managers/BusinessProviderManager.cs
> +                return id = _storage.Products.Max(products => products.Pastry.Id) + 1;
it can be just
return _storage.Products.Max(products => products.Pastry.Id) + 1;

and rename "products" to "product" cause it is single element

2021-06-01 18:42 UTC, yevhenbilushko commented on PastriesDelivery/Managers/BusinessProviderManager.cs
> +            int id = default;
it can be removed

2021-06-01 18:42 UTC, yevhenbilushko commented on PastriesDelivery/Program.cs
> +
remove line

2021-06-01 18:42 UTC, yevhenbilushko commented on PastriesDelivery/DiscountPerscentConstants.cs
> +    public enum DiscountPercents
please move "DiscountPercents" and "Role" to folders
not to exist on the same level as "Program" file

2021-06-01 18:44 UTC, yevhenbilushko commented on PastriesDelivery/Constants.cs
> +        TwentyUnits = 2,
so seems like you do not need enum you need constants
you can make it later

2021-06-01 18:44 UTC, yevhenbilushko commented
looks good to me

2021-06-02 16:12 UTC, serhii-shkodenko requested changes
Поправь, пожалуйста, опечатку и будет мой аппрув.

2021-06-02 16:12 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/СustomerManager.cs
> +        public bool CheckForDataPrescence()
Опечатка в имени метода. Должно быть `Presence`.

2021-06-02 16:26 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-06-02 16:28 UTC, merged