Regex patterns
ViktoriiaKlymenko/HomeWorks pull request #4
Opened 2021-05-10 14:35 UTC by ViktoriiaKlymenko

2021-05-11 21:46 UTC, serhii-shkodenko requested changes

2021-05-11 21:46 UTC, serhii-shkodenko commented on PastriesDelivery/RegexPatterns.cs
> +            Addresses = new List<string> { @"улица\s[А-Я][а-я]*\,\sд\.\s\d{2}\,\sкв\.\s\d{2}",    // улица Серебряная, д. 23, кв. 89
Эти паттерны можно сократить буквально до одного. Этим и хороши регулярные выражения.

2021-05-11 21:46 UTC, serhii-shkodenko commented on PastriesDelivery/RegexPatterns.cs
> +            PhoneNumbers = new List<string> { @"\+380\(\d{2}\)\d{3}\s*\d{2}\s*\d{2}" ,         // +380(95)222 33 88
Эти паттерны можно сократить буквально до одного. Этим и хороши регулярные выражения.

2021-06-02 16:32 UTC, serhii-shkodenko requested changes

2021-06-02 16:32 UTC, serhii-shkodenko commented on PastriesDelivery/Contracts/IRegexPatterns.cs
> +    public interface IRegexPatterns
Здесь ты разделила сам процесс валидации от паттернов, которым должны соответвовать введенные пользователем данные. Идея такого разделения хорошая, однако это реализация не учитывает всех возможных опций валидации и является скорее оверижинирингом. 

Поэтому я предлагаю:
1. Этот интерфейс удалить. Сами паттерны прописать прямо в методах валидатора. 
2. Класс валидатора сделать статическим или обязать его реализоваиь интерфейс. 
3. Если будешь реализовывать интерфейс, не забудь сделать инъекцию в конструктор.

2021-06-03 13:39 UTC, ViktoriiaKlymenko commented on PastriesDelivery/Contracts/IRegexPatterns.cs
> +    public interface IRegexPatterns
сделала статическим класс и туда паттерны прописала в виде статических полей

2021-06-03 14:32 UTC, merged