Logger
ViktoriiaKlymenko/HomeWorks pull request #6
Opened 2021-05-15 19:11 UTC by ViktoriiaKlymenko

2021-06-02 16:59 UTC, serhii-shkodenko requested changes

2021-06-02 16:59 UTC, serhii-shkodenko commented on PastriesDelivery/Contracts/ILogger.cs
> +        void CreateFile();
Логер служит цели логирования, как именно он это делает - это деталь реализации. То есть он может пиать файл, может обращаться по сети и так далее. Поэтому этот метод нужно удалить из интерфейса.

2021-06-02 16:59 UTC, serhii-shkodenko commented on PastriesDelivery/Contracts/ILogger.cs
> +        void LogChanges(string message);
Будет достаточно назвать этот метод `Log()`.

2021-06-02 16:59 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/Logger.cs
> +        public void CreateFile()
Учитывая то, что я написал об интерфейсе, предлагаю или сделать этот метод приватным или удалить полностью, если он не нужен.

2021-06-02 16:59 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/Logger.cs
> +        public string FileName { get; set; }
Это публичное свойство с публичным сеттером. То есть ты позволяешь вызывающему коду менять имя файла. Такие опции задаются обычно один раз при создании объекта. Поэтому или добавь имя файла в конструктор, или запиши в приватную константу.

2021-06-03 19:36 UTC, serhii-shkodenko requested changes
Непосредственно к логгеру замечаний нет, плиз, поправь это и будет аппрув.

2021-06-03 19:36 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/СustomerManager.cs
> +        protected ILogger Logger { get; }
Добавь модификатор `readonly`.

2021-06-03 19:36 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/СustomerManager.cs
> +        protected IStorage Storage { get; }
Добавь модификатор `readonly`.

2021-06-03 19:36 UTC, serhii-shkodenko commented on PastriesDelivery/Program.cs
> +        private static void WorkWithProvider(Pastry pastry, Storage storage, Logger logger)
Вместо конкретных имплементаций, проси в параметрах асбракции. (Для модели `Pastry` - не нужно).

2021-06-03 19:36 UTC, serhii-shkodenko commented on PastriesDelivery/Program.cs
> +        private static void WorkWithConsumer(Pastry pastry, Storage storage, Logger logger)
Вместо конкретных имплементаций, проси в параметрах асбракции. (Для модели `Pastry` - не нужно).

2021-06-03 19:36 UTC, serhii-shkodenko commented on PastriesDelivery/Program.cs
> +        private static void WorkWithBusinessClient(Pastry pastry, Storage storage, Logger logger)
Вместо конкретных имплементаций, проси в параметрах асбракции. (Для модели `Pastry` - не нужно).

2021-06-03 19:36 UTC, serhii-shkodenko commented on PastriesDelivery/UI/CustomerUI.cs
> +        protected ICustomerManager Manager { get; }
Не хватает модификатора `readonly`.

2021-06-05 08:35 UTC, serhii-shkodenko requested changes
Из-за этого, что вмержен был 4 ПР случайно без аппрува, придется здесь его поправить. По логеру только одно небольшое замечание. Поправь, пожалуйста, и будет апрув.

2021-06-05 08:35 UTC, serhii-shkodenko commented on PastriesDelivery/Contracts/IRegexPatterns.cs
> +    public interface IRegexPatterns
У тебя валидатор статический класс. Зачем тебе этот интерфейс?

2021-06-05 08:35 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +        private static string Addresses { get; } = @"(?:�����|��\.?)\s?[�-�][�-�]*\.?\,?\s(?:���|�\.?)\s?\d{2}(?:\,\s?(?:��������|��\.?)\s?\d{2}|)$";
Этот паттерн ен работает.

![Screenshot 2021-06-05 112912](https://user-images.githubusercontent.com/69808191/120885396-504dd380-c5f1-11eb-82e6-5ae57d17dadf.png)

2021-06-05 08:35 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +            return regex.IsMatch(address) is true;
Достаточно вернуть просто `regex.IsMatch(address)`.

2021-06-05 08:35 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +            return regex.IsMatch(phoneNumber) is false;
Достаточно просто

`return regex.IsMatch(phoneNumber);`

2021-06-05 08:35 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +        public static bool ValidateAddress(string address)
Обрати внимание, как называется метод `regex.IsMatch()`. Обычно методы возвращающие bool назваются так, чтобы содержать в своем имени слово `Is` или `Has`. Переименуй, пожалуйста.

2021-06-05 08:35 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +        public static bool ValidatePhoneNumber(string phoneNumber)
Обрати внимание, как называется метод `regex.IsMatch()`. Обычно методы возвращающие bool назваются так, чтобы содержать в своем имени слово `Is` или `Has`. Переименуй, пожалуйста.

2021-06-05 08:35 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/Logger.cs
> +                writer.WriteLine($"{message} [{DateTime.Now:HH:mm}]");
Обычно сначала пишут дату, а потом сообщение. Так удобнее искать.

2021-06-05 09:38 UTC, ViktoriiaKlymenko commented on PastriesDelivery/Managers/DataValidator.cs
> +        private static string Addresses { get; } = @"(?:�����|��\.?)\s?[�-�][�-�]*\.?\,?\s(?:���|�\.?)\s?\d{2}(?:\,\s?(?:��������|��\.?)\s?\d{2}|)$";
Сменила кодировку на UTF-8, теперь должно работать

2021-06-05 09:41 UTC, serhii-shkodenko requested changes

2021-06-05 09:41 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +        public static bool IsValidateAddress(string address)
По английски звучать будет лучше так: `IsAddressValid()`.

2021-06-05 09:41 UTC, serhii-shkodenko commented on PastriesDelivery/Managers/DataValidator.cs
> +        public static bool IsValidatePhoneNumber(string phoneNumber)
По английски звучать будет лучше так: `IsPhoneNumberValid()`.

2021-06-05 09:51 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-06-05 10:01 UTC, merged